const CACHE='dungeon-survivor-v0.3.2';
const PRECACHE=[
 './','./index.html','./style.css','./game.js','./manifest.json','./icon-192.png','./icon-512.png','./splash-screen.png','./menu-screen.png','./assets/sprites/player.png','./assets/sprites/bat.png','./assets/sprites/goblin.png','./assets/sprites/skeleton.png','./assets/sprites/boss_mage.png',
 './assets/floor/floor_tiles.png','./floor_tiles.png','./floor-tiles-atlas.png',
 './floor-clean-1.png','./floor-clean-2.png','./floor-clean-3.png','./floor-clean-4.png','./floor-debris-1.png','./floor-debris-2.png','./floor-debris-3.png','./floor-debris-4.png','./floor-moss-1.png','./floor-moss-2.png','./floor-moss-3.png','./floor-moss-4.png',
 './assets/audio/combat/sword_swing_light.wav','./assets/audio/combat/sword_swing_heavy.wav','./assets/audio/combat/sword_hit.wav','./assets/audio/combat/sword_clang.wav','./assets/audio/combat/enemy_hit.wav','./assets/audio/combat/player_hurt.wav','./assets/audio/combat/enemy_death.wav','./assets/audio/combat/boss_death.wav','./assets/audio/magic/projectile_launch.wav','./assets/audio/magic/fireball_launch.wav','./assets/audio/magic/fire_impact.wav','./assets/audio/magic/magic_hit.wav','./assets/audio/loot/coin_pickup.wav','./assets/audio/loot/health_pickup.wav','./assets/audio/loot/weapon_pickup.wav','./assets/audio/UI/ui_denied.wav','./assets/audio/UI/game_over.wav','./assets/audio/UI/level_up.wav','./assets/audio/UI/wave_warning.wav','./assets/audio/UI/boss_warning.wav','./assets/audio/UI/ui_click.wav','./assets/audio/UI/ui_confirm.wav','./assets/audio/world/footstep_stone.wav','./assets/audio/world/door_open.wav','./assets/audio/world/door_close.wav','./assets/audio/world/dungeon_drip.wav','./assets/audio/world/torch_crackle.wav','./assets/audio/world/room_clear.wav','./assets/audio/world/exit_activate.wav','./assets/audio/world/shop_open.wav','./assets/audio/world/teleport.wav', './assets/loot/gold.png','./assets/loot/health-small.png','./assets/loot/health-full.png','./assets/loot/weapon-drop.png','./assets/projectiles/goblin-arrow.png','./assets/projectiles/fireball.png','./assets/projectiles/fireblast.png','./assets/effects/impact-spark.png','./assets/effects/hit-spark.png','./assets/effects/blood-splat.png','./assets/remains/skeleton-remains.png','./assets/remains/goblin-remains.png','./assets/remains/bat-remains.png','./assets/remains/boss-remains.png', './assets/props/torch-1.png','./assets/props/torch-2.png','./assets/props/torch-3.png','./assets/props/torch-4.png','./assets/props/chest-closed.png','./assets/props/chest-open.png','./assets/props/crate-1.png','./assets/props/crate-stack.png','./assets/props/barrel.png','./assets/props/pottery.png','./assets/props/ruined-pillar.png','./assets/props/rubble.png','./assets/props/statue.png',
 './walls/top/top-wall-clean-1.png','./assets/walls/top/top-wall-clean-1.png','./walls/top/top-wall-clean-2.png','./assets/walls/top/top-wall-clean-2.png','./walls/top/top-wall-clean-3.png','./assets/walls/top/top-wall-clean-3.png','./walls/top/top-wall-cracked-1.png','./assets/walls/top/top-wall-cracked-1.png','./walls/top/top-wall-cracked-2.png','./assets/walls/top/top-wall-cracked-2.png','./walls/top/top-wall-cracked-3.png','./assets/walls/top/top-wall-cracked-3.png','./walls/top/top-wall-mossy-1.png','./assets/walls/top/top-wall-mossy-1.png','./walls/top/top-wall-mossy-2.png','./assets/walls/top/top-wall-mossy-2.png','./walls/top/top-wall-mossy-3.png','./assets/walls/top/top-wall-mossy-3.png',
 './walls/left/left-wall-clean.png','./assets/walls/left/left-wall-clean.png','./walls/right/right-wall-clean.png','./assets/walls/right/right-wall-clean.png','./walls/bottom/bottom-wall-clean.png','./assets/walls/bottom/bottom-wall-clean.png',
 './top-wall-clean.png','./top-wall-cracked.png','./top-wall-mossy.png','./left-wall-clean.png','./right-wall-clean.png','./bottom-wall-clean.png'
];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(async cache=>{await Promise.allSettled(PRECACHE.map(u=>cache.add(u)));}).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;
 e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{});return r}).catch(()=>caches.match(e.request)));
});
